- name: Install MariaDB server & client
  become: true
  apt: "{{mysql_pkg:}}"
  
- name: Install Pip
  become: true
  ansible.builtin.apt: 
    update_cache: yes 
    pkg: "{{pip_pkg}}"

- name: Pip PyMySQL
  pip:
    name: pymysql
    state: present  

- name: Create user for DB
  community.mysql.mysql_user:
    login_unix_socket: /run/mysqld/mysqld.sock
    check_implicit_admin: yes
    login_user: root
    login_password: "{{db_login_pwd}}"
    name: ecommerce
    password: "{{mysql_pwd}}"
    priv: '*.*:ALL'
    state: present