---
# vars file for install-php
php_certificates : 
      - apt-transport-https
      - lsb-release
      - ca-certificates
      - git
      - unzip
composer_install_dir: /usr/local/bin
php_modules: 
      - php8.2-cli
      - php8.2-common
      - php8.2-mysql
      - php8.2-zip
      - php8.2-gd
      - php8.2-mbstring
      - php8.2-curl
      - php8.2-xml
      - php8.2-bcmath
