- name: install certificates
  apt:
    pkg: 
      - apt-transport-https
      - lsb-release
      - ca-certificates

- name: Add Sury PPA repo for php8.0
  shell: |
    wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
- name: apt update
  apt:
    update_cache: yes

- name: Checking whether Composer is installed
  stat:
    path: "{{composer_install_dir}}/composer"
  register: composer_path

- name: Install Composer
  ansible.builtin.apt:
    name: composer
    state: latest
  when: composer_path.stat.exists == False

- name: Install additionnal modules
  ansible.builtin.apt:
    pkg: "{{php_modules}}"