version: '3'

services:
  database:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_USER: ${MARIADB_USER:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
    env_file:
      - .env
    ports:
      - ${MARIADB_PORT:-5432}:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql:rw
