nelmio_api_doc:
    documentation:
        info:
            title: Trottin'Old API
            description: This is an awesome E-Commerce API!
            version: 1.0.0
        components:
          securitySchemes:
            bearerAuth:           
              type: http
              scheme: bearer
              bearerFormat: JWT 
          responses:
            UnauthorizedError:
              description: Access token is missing or invalid
        # By default all routes are secured and require a bearer token
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api/(?!doc(\.json)?$) # Accepts routes under /api except /api/doc
