name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  prod_deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Write hosts file
      run: |
          HOST_CONTENT=$(cat << EOF
          [web]
          web-1 ansible_ssh_host=${{secrets.PROD_IP}} ansible_user=${{secrets.PROD_USER}} ansible_port=${{secrets.PROD_PORT}}
          EOF
          )
          echo "$HOST_CONTENT" > hosts

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        name: id_ed25519
        known_hosts: ${{ secrets.PROD_KNOWN_HOSTS }}
        if_key_exists: fail

    - name: Be sure the VM is powered ON
      run: |
        curl -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_TOKEN }}" \
        -d '{"type":"power_on"}' \
        "https://api.digitalocean.com/v2/droplets/${{ secrets.DIGITALOCEAN_PROD_DROPLET }}/actions"

        echo -e "\nWait 30sec for the droplet to be on"
        sleep 30

    - name: Run deployment
      run: ansible-playbook playbook.yml -i hosts --extra-vars "ansible_sudo_pass=${{ secrets.PROD_SUDO_PWD }}"
